---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  storageClassName: git-volume
  hostPath:
    path: /data/git
