---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galaxy

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: galaxy-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

images:
  - name: pulp/pulp-galaxy-ng
    newTag: latest

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - ingress.yaml
  - service.yaml
  - configmap.yaml
  - deployment.yaml
