---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: galaxy-volume
  hostPath:
    path: /data/galaxy
