---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: azuredns-config
    type: Opaque
    literals:
      - client-secret=0000000000000000000000000000000000

resources:
  - issuer.yaml
