---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galaxy

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: galaxy-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: galaxy-postgres-configuration
    type: Opaque
    literals:
      - host=galaxy-database-svc
      - port=5432
      - database=galaxy
      - username=galaxy
      - password=Galaxy123!
      - sslmode=prefer
      - type=managed

  - name: galaxy-admin-password
    type: Opaque
    literals:
      - password=Galaxy123!

resources:
  - pv.yaml
  - galaxy.yaml
