---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-database-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: galaxy-database-volume
  hostPath:
    path: /data/galaxy/database

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-file-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: galaxy-file-volume
  hostPath:
    path: /data/galaxy/file

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-redis-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  storageClassName: galaxy-redis-volume
  hostPath:
    path: /data/galaxy/redis
